Force correct Akka version when running tests
Without this dependency, tests fail with a NoSuchMethodError, which is
almost always a result of binary incompatibility.  The error points at
Akka and Typesafe Config as the culprits.  Forcing the same version in
the test configuration as in the compile configuration fixes the issue.